name: Build and Test Plugin Workflow

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    name: Build and Test Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Set-up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Checkout Plugin
        uses: actions/checkout@v2

      - name: Build Plugin
        run: ./gradlew build
